name: Matrix Demo
on: push
jobs:
  build:
    strategy:
      matrix:
        node-version: [18, 20]
        operating-system: [ubuntu-latest, windows-latest]
        include: 
          - node-version: 22
            operating-system: ubuntu-latest
        exclude:
          - node-version: 18
            operating-system: windows-latest
    runs-on: ${{ matrix.operating-system  }}
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: Install NodeJs
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependecies
        run: npm ci
      - name: Build project
        run: npm run build
